listaEmails = {
    'Adriana Ferreira Costa':'adriana.costa@colegioapogeu.com.br',
    'Adriano Tadini e Barros':'adriano.barros@colegioapogeu.com.br',
    'Alexandre Fidelis':'alexandre.fidelis@colegioapogeu.com.br',
    'Aline Gabriel Barbosa':'aline.barbosa@colegioapogeu.com.br',
    'Almir Pecoraro Junior':'almir.junior@colegioapogeu.com.br',
    'Amanda de Castro Rezende':'amanda.rezende@colegioapogeu.com.br',
    'Amanda Márcia Dominato Da Ana':'amanda.ana@colegioapogeu.com.br',
    'Amanda Martins Barbosa':'amanda.barbosa@colegioapogeu.com.br',
    'Amanda Miranda Ribeiro':'amanda.ribeiro@colegioapogeu.com.br',
    'Amanda Ribeiro da Costa':'amanda.costa@colegioapogeu.com.br',
    'Ana Carolina Machado Castro':'ana.carolina@colegioapogeu.com.br',
    'Ana Caroline Nogueira Rodrigues Melgaço':'ana.melgaco@colegioapogeu.com.br',
    'Ana Letycia de Oliveira Souza Rodrigues':'ana.letycia@colegioapogeu.com.br',
    'Ana Paula Calichio':'ana.calichio@colegioapogeu.com.br',
    'Ana Paula Machado':'ana.machado@colegioapogeu.com.br',
    'Andreia Silva Damasceno':'andreia.damasceno@colegioapogeu.com.br',
    'Ane Elyse Fernandes Silva':'ane.silva@colegioapogeu.com.br',
    'Angela Cristina Moreira':'angela.moreira@colegioapogeu.com.br',
    'Angelo Augusto Nogueres':'angelo.nogueres@colegioapogeu.com.br',
    'Annie Amaro da Silva':'annie.silva@colegioapogeu.com.br',
    'Barbara Bruna Muniz Figueiredo':'barbara.figueiredo@colegioapogeu.com.br',
    'Benedita Rita Silva Avila':'benedita.avila@colegioapogeu.com.br',
    'Breno Alves Teodoro':'breno.teodoro@colegioapogeu.com.br',
    'Bruna Thalita de Lima Pereira':'bruna.pereira@colegioapogeu.com.br',
    'Bruno de Souza Gonçalves':'bruno.goncalves@colegioapogeu.com.br',
    'Bruno Leandro de Oliveira Costa':'bruno.costa@colegioapogeu.com.br',
    'Bruno Rodrigues':'bruno.rodrigues@colegioapogeu.com.br',
    'Cacilda Frazzatto de Paula':'cacilda.frazzatto@colegioapogeu.com.br',
    'Caio Campos Araújo Pádua':'caio.padua@colegioapogeu.com.br',
    'Caio César de Paiva':'caio.paiva@colegioapogeu.com.br',
    'Camila Aparecida Braga de Oliveira':'camila.oliveira@colegioapogeu.com.br',
    'Carlos Alberto Teixeira de Souza':'carlos.souza@colegioapogeu.com.br',
    'Carlos Augusto Pereira':'carlos.pereira@colegioapogeu.com.br',
    'Carolina Ramos de Souza':'carolina.souza@colegioapogeu.com.br',
    'Carolina Rezende Moreira de Oliveira':'carolina.oliveira@colegioapogeu.com.br',
    'Celso Guimarães Brandão':'celso.brandao@colegioapogeu.com.br',
    'Charles Dias Gonçalves':'charles.goncalves@colegioapogeu.com.br',
    'Christian Blenke':'christian.blenke@colegioapogeu.com.br',
    'Christiano Landau de Carvalho Hilgemberg':'christiano.landau@colegioapogeu.com.br',
    'Cintia Laviola de Almeida':'cintia.almeida@colegioapogeu.com.br',
    'Cleverson Miranda Natali':'cleverson.miranda@colegioapogeu.com.br',
    'Corine Viana de Medeiros':'corine.medeiros@colegioapogeu.com.br',
    'Daniel Mendes Coutinho':'daniel.coutinho@colegioapogeu.com.br',
    'Danielle Morais Generoso':'danielle.generoso@colegioapogeu.com.br',
    'Danilo Januário Braz':'danilo.braz@colegioapogeu.com.br',
    'David Militão Campos de Oliveira':'david.militao@colegioapogeu.com.br',
    'Deborah de Oliveira Costa':'deborah.costa@colegioapogeu.com.br',
    'Diego Miranda Natali':'diego.natali@colegioapogeu.com.br',
    'Dimas Guido Silva':'dimas.silva@colegioapogeu.com.br',
    'Edmond Neto de Oliveira':'edmond.oliveira@colegioapogeu.com.br',
    'Eduarda Jaira de Amorim':'eduarda.amorim@colegioapogeu.com.br',
    'Eduardo Brandi Marques':'eduardo.marques@colegioapogeu.com.br',
    'Eduardo da Silva Miranda':'eduardo.miranda@colegioapogeu.com.br',
    'Eduardo Yassuo Araki':'eduardo.araki@colegioapogeu.com.br',
    'Eider Coelho Moreira':'eider.moreira@colegioapogeu.com.br',
    'Eleonora Moreira Cardoso Lasmar':'eleonora.lasmar@colegioapogeu.com.br',
    'Elias Arantes Landim':'elias.landim@colegioapogeu.com.br',
    'Eloy Bhering Leite Praça':'eloy.bhering@colegioapogeu.com.br',
    'Elza Mayra de Oliveira Silva':'elza.silva@colegioapogeu.com.br',
    'Erica Maria Bueno':'erica.bueno@colegioapogeu.com.br',
    'Erick dos Santos Teixeira':'erick.teixeira@colegioapogeu.com.br',
    'Fabiana Aparecida da Silva Almeida':'fabiana.almeida@colegioapogeu.com.br',
    'Fabiana de Sá Pereira':'fabiana.pereira@colegioapogeu.com.br',
    'Fabiane de Oliveira Costa':'fabiane.costa@colegioapogeu.com.br',
    'Fabio Jorge Duarte Lima':'fabio.lima@colegioapogeu.com.br',
    'Fabricio Acauhi Costa dos Santos':'fabricio.santos@colegioapogeu.com.br',
    'Fabricio Soares Carvalho de Oliveira':'fabricio.oliveira@colegioapogeu.com.br',
    'Felipe Eduardo Machado de Oliveira':'felipe.oliveira@colegioapogeu.com.br',
    'Felipe Rocha da Silva Santos':'felipe.santos@colegioapogeu.com.br',
    'Fernanda de Oliveira Marques':'fernanda.marques@colegioapogeu.com.br',
    'Fernanda Faustino Matos':'fernanda.matos@colegioapogeu.com.br',
    'Fernanda Henriques Canedo de Souza':'fernanda.souza@colegioapogeu.com.br',
    'Fernanda Louise Cisne Lemos Cardozo Honorio':'fernanda.honorio@colegioapogeu.com.br',
    'Fernando Araújo de Almeida':'fernando.almeida@colegioapogeu.com.br',
    'Filipi Fernandes':'filipi.fernandes@colegioapogeu.com.br',
    'Flaviane Marques de Almeida Gonçalves':'flaviane.goncalves@colegioapogeu.com.br',
    'Flaviany Moraes Silveira':'flaviany.silveira@colegioapogeu.com.br',
    'Francieli Vieira da Silva Costa':'francieli.costa@colegioapogeu.com.br',
    'Francisca Junia Macieira':'francisca.macieira@colegioapogeu.com.br',
    'Frederico Clemente Gardel':'frederico.gardel@colegioapogeu.com.br',
    'Gabriel Albuquerque de Matos Assis':'gabriel.matos@colegioapogeu.com.br',
    'Gabriel Augusto Morgado Pereira':'gabriel.pereira@colegioapogeu.com.br',
    'Gabriel Ribeiro Telles Ferreira':'gabriel.ferreira@colegioapogeu.com.br',
    'Gabriela Braga Guarabyra':'gabriela.guarabyra@colegioapogeu.com.br',
    'Gabriela Karpichin':'gabriela.karpichin@colegioapogeu.com.br',
    'Gabriella Barcellos Faria':'gabriella.faria@colegioapogeu.com.br',
    'Giani Batista da Silva':'giani.silva@colegioapogeu.com.br',
    'Gilmara Aparecida Valente de Mendonça':'gilmara.mendonca@colegioapogeu.com.br',
    'Glaucileia de Oliveira Poncilio Rodrigues':'glaucileia.rodrigues@colegioapogeu.com.br',
    'Glaucilene Souza da Silva':'glaucilene.silva@colegioapogeu.com.br',
    'Gleids Lane da Silva Lodoro Oliveira':'gleids.lodoro@colegioapogeu.com.br',
    'Grasiele Ferreira Rodrigues':'grasiele.rodrigues@colegioapogeu.com.br',
    'Graziela Miranda':'graziela.miranda@colegioapogeu.com.br',
    'Guilherme Augusto da Silveira':'guilherme.silveira@colegioapogeu.com.br',
    'Guilherme Lopes Galvão':'guilherme.galvao@colegioapogeu.com.br',
    'Guilherme Oliveira Drumond':'guilherme.drumond@colegioapogeu.com.br',
    'Guilherme Santos Timossi':'guilherme.timossi@colegioapogeu.com.br',
    'Gustavo Grizendi Tostes':'gustavo.tostes@colegioapogeu.com.br',
    'Gustavo Henrique da Silva Teixeira':'gustavo.teixeira@colegioapogeu.com.br',
    'Iara Neme Fontes':'iara.fontes@colegioapogeu.com.br',
    'Ícaro Rodrigues da Rocha':'icaro.rodrigues@colegioapogeu.com.br',
    'Isabel Marques Inácio Almeida':'isabel.almeida@colegioapogeu.com.br',
    'Isabela Lopes Costa':'isabela.lopes@colegioapogeu.com.br',
    'Isabella Martins de Almeida':'isabella.almeida@colegioapogeu.com.br',
    'Jackeline Nogueira Paes':'jackeline.paes@colegioapogeu.com.br',
    'Jacqueline Condé Martins':'jacqueline.martins@colegioapogeu.com.br',
    'Jacyara da Silva Melo Ferreira':'jacyara.ferreira@colegioapogeu.com.br',
    'Jacyara Soares Dias':'jacyara.dias@colegioapogeu.com.br',
    'Jader Arierom da Silva Moreira':'jader.moreira@colegioapogeu.com.br',
    'Joab Pereira da Silva':'joab.silva@colegioapogeu.com.br',
    'João Bruno de Oliveira Silva':'joao.silva@colegioapogeu.com.br',
    'Joelson Lopes da Silva':'joelson.silva@colegioapogeu.com.br',
    'Jorge Felipe Barbosa Mota':'jorge.felipe@colegioapogeu.com.br',
    'Jorge Oliveira de Faria':'jorge.faria@colegioapogeu.com.br',
    'Jose Carlos Fellet':'jose.fellet@colegioapogeu.com.br',
    'Jose Henrique Amorim Arbex':'jose.arbex@colegioapogeu.com.br',
    'Josiane Dias Gonçalves':'josiane.dias@colegioapogeu.com.br',
    'Julia Castro de Campos Hessel':'julia.hessel@colegioapogeu.com.br',
    'Juliana Canavan Martins Junqueira':'juliana.junqueira@colegioapogeu.com.br',
    'Juliana da Costa Oliveira':'juliana.oliveira@colegioapogeu.com.br',
    'Juliana de Oliveira Menezes':'juliana.menezes@colegioapogeu.com.br',
    'Juliana de Souza São Paulo Ruela':'juliana.ruela@colegioapogeu.com.br',
    'Juliana Fernandes de Oliveira':'juliana.fernandes@colegioapogeu.com.br',
    'Juliano Xavier de Figueiredo':'juliano.figueiredo@colegioapogeu.com.br',
    'Karla Ramim Reis de Mendonça':'karla.mendonca@colegioapogeu.com.br',
    'Karoline Flores Ferreira':'karoline.ferreira@colegioapogeu.com.br',
    'Keila Ferreira Martins':'keila.martins@colegioapogeu.com.br',
    'Kenia Ornelas Fonseca Barbosa Figueiredo':'kenia.figueiredo@colegioapogeu.com.br',
    'Lara Fernandes Lessa':'lara.lessa@colegioapogeu.com.br',
    'Larissa de Souza Oliveira':'larissa.oliveira@colegioapogeu.com.br',
    'Larissa Ferreira dos Santos':'larissa.ferreira@colegioapogeu.com.br',
    'Larissa Moreira Pícoli':'larissa.picoli@colegioapogeu.com.br',
    'Laura Júlia Alves de Paula':'laura.paula@colegioapogeu.com.br',
    'Laurentino Mendes Moratório Júnior':'laurentino.junior@colegioapogeu.com.br',
    'Leandro Bernardo dos Santos':'leandro.santos@colegioapogeu.com.br',
    'Leonardo Lima Costa':'leonardo.lima@colegioapogeu.com.br',
    'Leony Dias Nobre':'leony.nobre@colegioapogeu.com.br',
    'Letícia Gonçalves Silvestre':'leticia.silvestre@colegioapogeu.com.br',
    'Loren Mylena Ferreira da Silva':'loren.silva@colegioapogeu.com.br',
    'Lorena Torres Falci':'lorena.falci@colegioapogeu.com.br',
    'Luan Deilton Santos Amorim':'luan.amorin@colegioapogeu.com.br',
    'Lucas Braga Pessanha':'lucas.pessanha@colegioapogeu.com.br',
    'Lucas de Rezende da Silva':'lucas.rezende@colegioapogeu.com.br',
    'Lucas Frederico Monteiro de Carvalho':'lucas.monteiro@colegioapogeu.com.br',
    'Luciana Batista Teixeira':'luciana.teixeira@colegioapogeu.com.br',
    'Luciana da Silva Santana':'luciana.santana@colegioapogeu.com.br',
    'Luisiane Lopes Peron Marçal':'luisiane.marcal@colegioapogeu.com.br',
    'Luiz Fernando Andrade Dantas':'luiz.dantas@colegioapogeu.com.br',
    'Luiza Cavalcanti Lima':'luiza.lima@colegioapogeu.com.br',
    'Maira Saporetti Carvalho':'maira.carvalho@colegioapogeu.com.br',
    'Manoel Juventino de Andrade Santana':'manoel.santana@colegioapogeu.com.br',
    'Marcele Guiducci de Oliveira':'marcele.oliveira@colegioapogeu.com.br',
    'Marcella Gava Grillo':'marcella.grillo@colegioapogeu.com.br',
    'Marcello Luiz de Sousa':'marcello.sousa@colegioapogeu.com.br',
    'Marcelo Bonoto Marques':'marcelo.bonoto@colegioapogeu.com.br',
    'Marcelo Vidal de Mendonça':'marcelo.vidal@colegioapogeu.com.br',
    'Márcia Cristina de Souza':'marcia.souza@colegioapogeu.com.br',
    'Marcilia Vilela Ribeiro':'marcilia.ribeiro@colegioapogeu.com.br',
    'Marcionilo Euro Carlos Neto':'marcionilo.neto@colegioapogeu.com.br',
    'Marcos Vinicio Rodrigues de Oliveira':'marcos.oliveira@colegioapogeu.com.br',
    'Maria Aparecida Chaves Freitas':'maria.freitas@colegioapogeu.com.br',
    'Maria Cristina de Almeida':'maria.cristina@colegioapogeu.com.br',
    'Maria Cristina Vasconcelos Leite':'maria.leite@colegioapogeu.com.br',
    'Maria Eduarda Ferreira Leal':'maria.leal@colegioapogeu.com.br',
    'Maria Ignez de Souza Lima Figueiredo':'maria.figueiredo@colegioapogeu.com.br',
    'Maria Ivonete Silva Melo':'maria.silva@colegioapogeu.com.br',
    'Maria Patricia do Nascimento':'maria.nascimento@colegioapogeu.com.br',
    'Maria Regina da Silva':'maria.regina@colegioapogeu.com.br',
    'Mariana de Souza Dias':'mariana.dias@colegioapogeu.com.br',
    'Mariane de Oliveira Fernandes':'mariane.fernandes@colegioapogeu.com.br',
    'Marianny Martins Fernandes':'marianny.fernandes@colegioapogeu.com.br',
    'Marilia Villanova Rodrigues':'marilia.rodrigues@colegioapogeu.com.br',
    'Marina Branco Soares da Costa':'marina.costa@colegioapogeu.com.br',
    'Marina Pacheco Rolim Ribeiro':'marina.ribeiro@colegioapogeu.com.br',
    'Mário de Jesus Barboza':'mario.barboza@colegioapogeu.com.br',
    'Maurelio Pereira Lopes':'maurelio.lopes@colegioapogeu.com.br',
    'Mayara Silva dos Santos':'mayara.santos@colegioapogeu.com.br',
    'Michelle Dimas Tavares da Silva':'michelle.silva@colegioapogeu.com.br',
    'Moyra Ribeiro Marques':'moyra.marques@colegioapogeu.com.br',
    'Naiara Aparecida de Faria':'naiara.faria@colegioapogeu.com.br',
    'Nayara Soares Pereira':'nayara.pereira@colegioapogeu.com.br',
    'Nicole de Almeida':'nicole.almeida@colegioapogeu.com.br',
    'Pâmela Xavier da Fonseca':'pamela.fonseca@colegioapogeu.com.br',
    'Patrícia Gonçalves da Silva Machado':'patricia.machado@colegioapogeu.com.br',
    'Patrícia Mendonça de Castro Barra':'patricia.barra@colegioapogeu.com.br',
    'Patrick Motta Osório Esper':'patrick.esper@colegioapogeu.com.br',
    'Paula Carvalho':'paula.carvalho@colegioapogeu.com.br',
    'Paula Lamas de Oliveira Prado':'paula.prado@colegioapogeu.com.br',
    'Paulo Sergio Gomes Negrão':'paulo.negrao@colegioapogeu.com.br',
    'Paulo Victor Guiducci Miranda':'paulo.miranda@colegioapogeu.com.br',
    'Pedro Batista Alves Filho':'pedro.filho@colegioapogeu.com.br',
    'Pedro Caruso Fracetti':'pedro.caruso@colegioapogeu.com.br',
    'Priscila da Silva Campos':'priscila.campos@colegioapogeu.com.br',
    'Rachel Alvim de Almeida Lawal':'rachel.alvim@colegioapogeu.com.br',
    'Rafaela de Aragão Turl Raposo':'rafaela.aragao@colegioapogeu.com.br',
    'Rafaela do Carmo Bassi':'rafaela.bassi@colegioapogeu.com.br',
    'Rafaela Guimarães Gonçalves Rezende':'rafaela.rezende@colegioapogeu.com.br',
    'Rainny Correa da Silva':'rainny.silva@colegioapogeu.com.br',
    'Raphael de Oliveira Reis':'raphael.reis@colegioapogeu.com.br',
    'Raphaella Diogo Ferrara Delgado':'raphaella.delgado@colegioapogeu.com.br',
    'Renália Rodrigues de Souza':'renalia.souza@colegioapogeu.com.br',
    'Renan Canavez Raposo':'renan.raposo@colegioapogeu.com.br',
    'Renata Dornelas de Andrade':'renata.andrade@colegioapogeu.com.br',
    'Renata Vieira Scanapieco':'renata.scanapieco@colegioapogeu.com.br',
    'Renato de Souza Alves':'renato.alves@colegioapogeu.com.br',
    'Ricardo Alexandre Marcelino Mesquita Santos':'ricardo.santos@colegioapogeu.com.br',
    'Ricardo Henrique Davis Leite':'ricardo.leite@colegioapogeu.com.br',
    'Ricardo Nunes Cardoso':'ricardo.nunes@colegioapogeu.com.br',
    'Roberto Carlos Andrade de Oliveira':'roberto.oliveira@colegioapogeu.com.br',
    'Robson Mendes Cancela':'robson.cancela@colegioapogeu.com.br',
    'Rodrigo Antunes e Castro':'rodrigo.castro@colegioapogeu.com.br',
    'Rodrigo Cruz Gonçalves':'rodrigo.cruz@colegioapogeu.com.br',
    'Rodrigo Morais Chaves':'rodrigo.chaves@colegioapogeu.com.br',
    'Rodrigo Silva Fonseca':'rodrigo.fonseca@colegioapogeu.com.br',
    'Rogeria Costa Monteiro Silva':'rogeria.silva@colegioapogeu.com.br',
    'Rosilaine Feliz Vieira Rodrigues':'rosilaine.rodrigues@colegioapogeu.com.br',
    'Sabrina Simão Ferraz':'sabrina.ferraz@colegioapogeu.com.br',
    'Seida Santos':'seida.santos@colegioapogeu.com.br',
    'Shirley Cristina Elias':'shirley.cristina@colegioapogeu.com.br',
    'Sibellius de Souza Bernardes':'sibellius.bernardes@colegioapogeu.com.br',
    'Silvana Teodoro Resende':'silvana.resende@colegioapogeu.com.br',
    'Simone da Silva Feliciano':'simone.feliciano@colegioapogeu.com.br',
    'Soraya Aparecida da Silva Pires':'soraya.pires@colegioapogeu.com.br',
    'Suzanne Silva Rodrigues de Morais':'suzanne.morais@colegioapogeu.com.br',
    'Tammy Vasconcelos Morais':'tammy.morais@colegioapogeu.com.br',
    'Taylor de Almeida Coutinho':'taylor.coutinho@colegioapogeu.com.br',
    'Taylor Fonseca de Paula':'taylor.fonseca@colegioapogeu.com.br',
    'Thainá Fradico Silva':'thaina.fradico@colegioapogeu.com.br',
    'Thais Garcia Sipriano':'thais.sipriano@colegioapogeu.com.br',
    'Thais Silva de Paula':'thais.paula@colegioapogeu.com.br',
    'Thais Soares Gonçalves':'thais.goncalves@colegioapogeu.com.br',
    'Thales Contim Fernandes':'thales.fernandes@colegioapogeu.com.br',
    'Thamires Dias Braim':'thamires.braim@colegioapogeu.com.br',
    'Thiago Andrade de Paula':'thiago.paula@colegioapogeu.com.br',
    'Thiago Antônio Xavier Simão':'thiago.xavier@colegioapogeu.com.br',
    'Thiago de Teive e Argolo Vieira':'thiago.teive@colegioapogeu.com.br',
    'Thiago Gerheim de Andrade':'thiago.andrade@colegioapogeu.com.br',
    'Tiago Simões Bernardes':'tiago.simoes@colegioapogeu.com.br',
    'Vânia da Silva Meirelles':'vania.meirelles@colegioapogeu.com.br',
    'Vânia de Oliveira':'vania.oliveira@colegioapogeu.com.br',
    'Vera Gláucia Nery de Freitas':'vera.freitas@colegioapogeu.com.br',
    'Vera Regina de Paula':'vera.paula@colegioapogeu.com.br',
    'Verusca Aparecida de Souza Leopoldino':'verusca.leopoldino@colegioapogeu.com.br',
    'Victor Emanuel Pinto Guedes':'victor.guedes@colegioapogeu.com.br',
    'Vinicius Almeida de Souza':'vinicius.souza@colegioapogeu.com.br',
    'Vinícius Rangel dos Santos':'vinicius.rangel@colegioapogeu.com.br',
    'Viviane Aparecida de Melo Moreira':'viviane.moreira@colegioapogeu.com.br',
    'Wagner Fernando de Castro':'wagner.castro@colegioapogeu.com.br',
    'Wallace Rosa Correa':'wallace.correa@colegioapogeu.com.br',
    'Wantuil Alexandre de Andrade Lima':'wantuil.lima@colegioapogeu.com.br',
    'Washington Faria de Oliveira':'washington.oliveira@colegioapogeu.com.br',
    'Wellington Clayton Silva':'wellington.silva@colegioapogeu.com.br',
    'Welson Augusto Ribeiro':'welson.ribeiro@colegioapogeu.com.br',
    'Wesley de Oliveira Ramos':'wesley.ramos@colegioapogeu.com.br',
    'Wesley Pontes da Costa':'wesley.costa@colegioapogeu.com.br'
}   